services:
  - type: web
    name: vm-ecommerce-frontend
    env: static
    buildCommand: npm run build:render
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
